apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: function-pipeline
spec:
  resources:
  - name: app-source
    type: git
  - name: app-image
    type: image
  params:
  - name: context
    type: string
    default: app
  tasks:
  - name: build-function
    taskRef:
      name: function-task
    params:
    - name: contextDir
      value: "${params.context}"
    resources:
      inputs:
      - name: source
        resource: app-source
      outputs:
      - name: builtImage
        resource: app-image
